require('dotenv').config({ path: 'C:\\Workspace\\Active\\MCC\\.env' });

module.exports = {
  apps: [
    {
      name: 'mav-console',
      script: 'server.mjs',
      cwd: 'C:\\Workspace\\Active\\MCC',
      interpreter: 'node',
      watch: false,
      autorestart: true,
      max_restarts: 5,
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        MAV_REPO_BRIDGE_URL: 'http://127.0.0.1:8790',
        OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
        OPENAI_BASE_URL: process.env.OPENAI_BASE_URL || 'http://192.168.1.12:4000',
        NVIDIA_NIM_API_KEY: process.env.NVIDIA_NIM_API_KEY || '',
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY || '',
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
        PROMETHEUS_URL: process.env.PROMETHEUS_URL || 'http://192.168.1.12:9090',
        MAV_RAG_URL: process.env.MAV_RAG_URL || 'http://192.168.1.12:8181',
        MAV_EXTRA_ROOTS: process.env.MAV_EXTRA_ROOTS || '',
        SUPABASE_URL: process.env.SUPABASE_URL || '',
        SUPABASE_SERVICE_KEY: process.env.SUPABASE_SERVICE_KEY || '',
        VITE_SUPABASE_URL: process.env.VITE_SUPABASE_URL || '',
        VITE_SUPABASE_ANON_KEY: process.env.VITE_SUPABASE_ANON_KEY || '',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      windowsHide: true,
    },
    {
      name: 'prometheus-sync',
      script: 'C:\\Workspace\\Active\\MCC\\scripts\\prometheus-sync.mjs',
      cwd: 'C:\\Workspace\\Active\\MCC',
      interpreter: 'node',
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      env_file: 'C:\\Workspace\\Active\\SEO-Agents-App\\.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      windowsHide: true,
    },
    {
      name: 'downloads-watcher',
      script: 'C:\\Users\\carte\\DownloadsOrganizer\\downloads_watcher.py',
      interpreter: 'C:\\Users\\carte\\DownloadsOrganizer\\.venv\\Scripts\\pythonw.exe',
      cwd: 'C:\\Users\\carte\\DownloadsOrganizer',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      windowsHide: true,
    },
    {
      name: 'mav-bridge',
      script: 'C:\\Workspace\\Active\\SEO-Agents-App\\scripts\\mav-bridge.mjs',
      cwd: 'C:\\Workspace\\Active\\SEO-Agents-App',
      interpreter: 'node',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env_file: 'C:\\Workspace\\Active\\SEO-Agents-App\\.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      windowsHide: true,
    },
    {
      name: 'mcc-dashboard-agent',
      script: 'agent.py',
      cwd: 'C:\\Workspace\\Shared\\Agents\\HomeLab-Agent',
      interpreter: 'C:\\Users\\carte\\AppData\\Local\\Programs\\Python\\Python312\\python.exe',
      watch: false,
      autorestart: true,
      max_restarts: 999,
      restart_delay: 5000,
      env_file: 'C:\\Workspace\\Shared\\Agents\\HomeLab-Agent\\.env',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      windowsHide: true,
    },
  ]
};
